# Default AI
# Specify which AI will be used: GPT or GEMINI
ai: "GPT"

# Custom command for AI requests
# You can set any command name instead of /ask.
# For example: "ask", "bot", "help", etc.
# If you change settings while the server is running, make sure to restart the server for the changes to take effect.
ask-command: "ask"

# Cooldown time in seconds between requests from the same player
cooldown-seconds: 30

# List of prefixes to use in chat.
# If prefixes are specified, the AI will only respond to messages starting with them.
# Leave the list empty to allow the AI to react to all messages in the chat.
# If you change settings while the server is running, make sure to restart the server for the changes to take effect.
prefixes:
  - "$"
  - "#"

##########################
#    OpenAI Settings     #
##########################
# Configure the OpenAI model here.
# You can obtain your API key from: https://platform.openai.com/api-keys
# Remember, using GPT is not free. You can top up your balance here:
# https://platform.openai.com/settings/organization/billing/overview

gpt-api-key: "your_openai_api_key"  # Your OpenAI API key
openai-model: "gpt-3.5-turbo"  # Specify the desired OpenAI model

# Token limit for AI responses.
# This limits the number of words and characters in the response.
max-tokens: 500

# The role of the AI, defining its communication style and context.
# Example: "Respond briefly and to the point. Ignore complex queries."
system-role: "You are interacting with players on a Minecraft server. Keep responses short, ideally a single sentence. Avoid long words and maintain the Minecraft chat format."

##########################
#    Gemini Settings     #
##########################
# Unlike GPT, using Gemini is free.
# You can obtain your API key here:
# https://console.cloud.google.com/apis/library/generativelanguage.googleapis.com

gemini-api-key: "your_gemini_api_key"  # Your Gemini API key
gemini-model: "gemini-1.0-pro-latest"  # Specify the desired Gemini model
