# AI по умолчанию
# Укажите, какой AI будет использоваться: GPT или GEMINI
ai: "GPT"

# Настраиваемая команда для запроса к AI
# Здесь вы можете задать любое название команды вместо /ask.
# Например: "спроси", "бот", "хелп" и т.п.
# Если вы меняете настройки при запущенном сервере, обязательно перезагрузите сервер чтобы изменения вступили в силу.
ask-command: "ask"
# Время кулдауна в секундах между запросами от одного игрока

cooldown-seconds: 30
# Список префиксов для использования в чате.
# Если указаны префиксы, AI активируется только на сообщения, которые начинаются с них.
# Оставьте список пустым, чтобы AI реагировал на все сообщения в чате.
# Если вы меняете настройки при запущенном сервере, обязательно перезагрузите сервер чтобы изменения вступили в силу.
prefixes:
  - "$"
  - "#"

##########################
#    Настройки OpenAI     #
##########################
# Здесь настраивается модель от OpenAI.
# API-ключ можно получить по ссылке: https://platform.openai.com/api-keys
# Помните, что использование GPT платное. Пополнить баланс можно здесь:
# https://platform.openai.com/settings/organization/billing/overview

gpt-api-key: "your_openai_api_key"  # Ваш ключ API OpenAI
openai-model: "gpt-3.5-turbo"  # Укажите нужную модель OpenAI

# Настройка лимита токенов для ответов AI.
# Это ограничение на количество слов и символов в ответе.
max-tokens: 500

# Роль AI, которая задаёт стиль и контекст общения.
# Например: "Отвечай кратко и по делу. Игнорируй сложные запросы."
system-role: "Ты общаешься с игроками на сервере Minecraft. Отвечай кратко, максимум одним предложением. Избегай длинных слов и поддерживай формат чата Minecraft."

##########################
#    Настройки Gemini     #
##########################
# В отличие от GPT, использование Gemini бесплатно.
# API-ключ можно получить по ссылке:
# https://console.cloud.google.com/apis/library/generativelanguage.googleapis.com

gemini-api-key: "your_gemini_api_key"  # Ваш ключ API Gemini
gemini-model: "gemini-1.0-pro-latest"  # Укажите нужную модель Gemini